// Mocks generated by Mockito 5.4.6 from annotations
// in news/test/features/news/presentation/bloc/news_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news/features/news/domain/entities/entities.dart' as _i6;
import 'package:news/features/news/domain/usecases/fetch_news_usecase.dart'
    as _i2;
import 'package:news/features/news/domain/usecases/get_news_usecase.dart'
    as _i5;
import 'package:news/features/news/domain/usecases/usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FetchNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNewsUseCase extends _i1.Mock implements _i2.FetchNewsUseCase {
  @override
  _i3.Future<void> call(_i4.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GetNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNewsUseCase extends _i1.Mock implements _i5.GetNewsUseCase {
  @override
  _i3.Stream<List<_i6.NewsEntity>> call(_i4.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Stream<List<_i6.NewsEntity>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i6.NewsEntity>>.empty(),
          )
          as _i3.Stream<List<_i6.NewsEntity>>);
}
