// Mocks generated by Mockito 5.4.6 from annotations
// in news/test/features/theme/presentation/bloc/theme_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news/config/themes/app_theme_mode.dart' as _i5;
import 'package:news/features/theme/domain/repositories/theme_repository.dart'
    as _i2;
import 'package:news/features/theme/domain/usecases/get_theme_usecase.dart'
    as _i3;
import 'package:news/features/theme/domain/usecases/save_theme_usecase.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThemeRepository_0 extends _i1.SmartFake
    implements _i2.ThemeRepository {
  _FakeThemeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetThemeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetThemeUseCase extends _i1.Mock implements _i3.GetThemeUseCase {
  MockGetThemeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ThemeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeThemeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ThemeRepository);

  @override
  _i4.Future<_i5.AppThemeMode> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.AppThemeMode>.value(
              _i5.AppThemeMode.light,
            ),
          )
          as _i4.Future<_i5.AppThemeMode>);
}

/// A class which mocks [SaveThemeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveThemeUseCase extends _i1.Mock implements _i6.SaveThemeUseCase {
  MockSaveThemeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ThemeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeThemeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ThemeRepository);

  @override
  _i4.Future<void> call(_i5.AppThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
