// Mocks generated by Mockito 5.4.6 from annotations
// in news/test/features/news/presentation/bloc/featured_news/featured_news_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news/features/news/domain/entities/entities.dart' as _i2;
import 'package:news/features/news/domain/usecases/fetch_featured_news_usecase.dart'
    as _i6;
import 'package:news/features/news/domain/usecases/get_featured_news_usecase.dart'
    as _i3;
import 'package:news/features/news/domain/usecases/usecase.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedNewsEntity_0 extends _i1.SmartFake
    implements _i2.PaginatedNewsEntity {
  _FakePaginatedNewsEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFeaturedNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFeaturedNewsUseCase extends _i1.Mock
    implements _i3.GetFeaturedNewsUseCase {
  MockGetFeaturedNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.NewsEntity?> call(_i5.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Stream<_i2.NewsEntity?>.empty(),
          )
          as _i4.Stream<_i2.NewsEntity?>);
}

/// A class which mocks [FetchFeaturedNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchFeaturedNewsUseCase extends _i1.Mock
    implements _i6.FetchFeaturedNewsUseCase {
  MockFetchFeaturedNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedNewsEntity> call(_i5.FetchNewsParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i2.PaginatedNewsEntity>.value(
              _FakePaginatedNewsEntity_0(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.PaginatedNewsEntity>);
}
