// Mocks generated by Mockito 5.4.6 from annotations
// in news/test/features/saves/presentation/bloc/save_status/save_status_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news/features/saves/domain/entities/entities.dart' as _i4;
import 'package:news/features/saves/domain/usecases/delete_news_usecase.dart'
    as _i7;
import 'package:news/features/saves/domain/usecases/get_save_status_usecase.dart'
    as _i2;
import 'package:news/features/saves/domain/usecases/save_news_usecase.dart'
    as _i6;
import 'package:news/features/saves/domain/usecases/usecase.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetSaveStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSaveStatusUseCase extends _i1.Mock
    implements _i2.GetSaveStatusUseCase {
  MockGetSaveStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.SavedNewsEntity?> call(_i5.GetSaveStatusParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.SavedNewsEntity?>.value(),
          )
          as _i3.Future<_i4.SavedNewsEntity?>);
}

/// A class which mocks [SaveNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveNewsUseCase extends _i1.Mock implements _i6.SaveNewsUseCase {
  MockSaveNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i5.SaveNewsParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DeleteNewsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNewsUseCase extends _i1.Mock implements _i7.DeleteNewsUseCase {
  MockDeleteNewsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i5.DeleteNewsParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
